name: Update Jira Custom Field - isPRApproved

on:
  pull_request_review:
    types:
      - submitted
jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Retrieve Issue Key from Branch Name
        id: split-branch-name
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BRANCH_NAME=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
            | jq -r '.head.ref')
          SECOND_PART=$(echo "$BRANCH_NAME" | cut -d'-' -f2-)
          echo "issue_key=$SECOND_PART" >> "$GITHUB_ENV"
        
      - name: Update Jira Custom Field - isPRApproved
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_BASIC_API_TOKEN }}
        run: |
          ISSUE_KEY="${{ env.issue_key }}"  # Replace with the Jira issue key
          API_ENDPOINT="/rest/api/2/issue/$ISSUE_KEY"  # Replace with the desired Jira API endpoint

          REQUEST_BODY='{
            "fields": {
              "customfield_10038": "${{ github.event.review.state }}"
            }
          }'

          curl --location --request PUT $JIRA_BASE_URL$API_ENDPOINT \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $JIRA_API_TOKEN" \
            -d "$REQUEST_BODY"
            
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
            
      - name: Transition issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.issue_key }}
          transition: "PR Approved"
        if: ${{ github.event.review.state == 'APPROVED' }}
